name="Bumho"
num=52.1
num2=34
num3=25
my_bool=True
my_list=["toyota","dodge"]
my_tuple=("kenya","uganda")
my_set={"mangoes","banana"}
print(type(name))
print(type(num))
print(type(num2))
print(type(num3))
print(type(my_tuple))
print(type(my_set))
print(type(my_list))
